// Leetcode problem #389. Find the Difference
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Constraints:
// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    let sFrequency = []
    for (let i = 0; i < 26; i++) {
        sFrequency.push(0)
    }
    for (let letter of s) {
        sFrequency[letter.charCodeAt(0) - 97]++
    }
    for (let letter of t) {
        sFrequency[letter.charCodeAt(0) - 97]--
    }
    for (let index = 0; index < sFrequency.length; index++) {
        if (sFrequency[index] < 0) {
            return String.fromCharCode(index + 97)
        }
    }
};


console.log(findTheDifference("abcd","abcde"));